# -*- coding: utf-8 -*-
from . import company
from . import student_migration
from . import student
from . import admission
from . import admission_record
from . import registration
from . import nationality_type
from . import fees
from . import year
from . import student_fees
from . import batch
from . import category
from . import post_payment
from . import secondry_result
from . import discount_scholarship
from . import discount_scholarship_request
from . import study_calendar
from . import identity_type
from . import fulfillment_subject
from . import account